"""initial_schema

Revision ID: 8e4b1bc41757
Revises: 
Create Date: 2026-07-04 15:17:01.551707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4b1bc41757'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('evolution_api_url', sa.String(), nullable=True),
    sa.Column('evolution_api_key', sa.String(), nullable=True),
    sa.Column('evolution_instance', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('google_calendar_id', sa.String(), nullable=True),
    sa.Column('firma_png_url', sa.String(), nullable=True),
    sa.Column('sello_png_url', sa.String(), nullable=True),
    sa.Column('color_principal', sa.String(), nullable=True),
    sa.Column('color_secundario', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('perfiles_veterinarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('matricula_profesional', sa.String(), nullable=True),
    sa.Column('nombre_veterinaria', sa.String(), nullable=True),
    sa.Column('firma_sello_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfiles_veterinarios_id'), 'perfiles_veterinarios', ['id'], unique=False)
    op.create_table('certificados_vacunacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_nombre', sa.String(), nullable=True),
    sa.Column('mascota_especie', sa.String(), nullable=True),
    sa.Column('dueno_nombre', sa.String(), nullable=True),
    sa.Column('veterinario_id', sa.Integer(), nullable=True),
    sa.Column('vacunas_json', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('hash_control', sa.String(), nullable=True),
    sa.Column('token_validacion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['veterinario_id'], ['perfiles_veterinarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_vacunacion_id'), 'certificados_vacunacion', ['id'], unique=False)
    op.create_index(op.f('ix_certificados_vacunacion_token_validacion'), 'certificados_vacunacion', ['token_validacion'], unique=True)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'phone_number', name='_org_phone_uc')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_index(op.f('ix_owners_org_id'), 'owners', ['org_id'], unique=False)
    op.create_index(op.f('ix_owners_phone_number'), 'owners', ['phone_number'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_org_id'), 'services', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('signature_img', sa.String(), nullable=True),
    sa.Column('stamp_img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('pet_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apps_org_date', 'appointments', ['org_id', 'date'], unique=False)
    op.create_index('idx_apps_org_status', 'appointments', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_org_id'), 'appointments', ['org_id'], unique=False)
    op.create_index(op.f('ix_appointments_owner_id'), 'appointments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_appointments_pet_name'), 'appointments', ['pet_name'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('medical_history_link', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'owner_id', 'name', name='_org_owner_pet_uc')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_org_id'), 'patients', ['org_id'], unique=False)
    op.create_index(op.f('ix_patients_owner_id'), 'patients', ['owner_id'], unique=False)
    op.create_table('professional_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('professional_registry', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('professional_email', sa.String(), nullable=True),
    sa.Column('professional_phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('social_media', sa.String(), nullable=True),
    sa.Column('signature_url', sa.String(), nullable=True),
    sa.Column('stamp_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_professional_identities_id'), 'professional_identities', ['id'], unique=False)
    op.create_table('registro_integridad_certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificado_id', sa.Integer(), nullable=True),
    sa.Column('hash_pdf', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificados_vacunacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_integridad_certificados_id'), 'registro_integridad_certificados', ['id'], unique=False)
    op.create_table('clinical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vet_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_records_id'), 'clinical_records', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_records_org_id'), 'clinical_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_clinical_records_patient_id'), 'clinical_records', ['patient_id'], unique=False)
    op.create_table('digital_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_certificates_file_hash'), 'digital_certificates', ['file_hash'], unique=True)
    op.create_index(op.f('ix_digital_certificates_id'), 'digital_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_digital_certificates_org_id'), 'digital_certificates', ['org_id'], unique=False)
    op.create_index(op.f('ix_digital_certificates_patient_id'), 'digital_certificates', ['patient_id'], unique=False)
    op.create_table('medical_attentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('vet_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_attentions_id'), 'medical_attentions', ['id'], unique=False)
    op.create_index(op.f('ix_medical_attentions_org_id'), 'medical_attentions', ['org_id'], unique=False)
    op.create_index(op.f('ix_medical_attentions_patient_id'), 'medical_attentions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_attentions_vet_id'), 'medical_attentions', ['vet_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('vaccine_name', sa.String(), nullable=True),
    sa.Column('date_administered', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_dose_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('vet_stamp', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_id'), 'vaccinations', ['id'], unique=False)
    op.create_index(op.f('ix_vaccinations_next_dose_date'), 'vaccinations', ['next_dose_date'], unique=False)
    op.create_index(op.f('ix_vaccinations_org_id'), 'vaccinations', ['org_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_patient_id'), 'vaccinations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_vaccine_name'), 'vaccinations', ['vaccine_name'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attention_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('ticket_number', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attention_id'], ['medical_attentions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attention_id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_org_id'), 'tickets', ['org_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=False)
    op.create_table('ticket_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_items_id'), 'ticket_items', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_items_ticket_id'), 'ticket_items', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_items_ticket_id'), table_name='ticket_items')
    op.drop_index(op.f('ix_ticket_items_id'), table_name='ticket_items')
    op.drop_table('ticket_items')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_org_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_vaccinations_vaccine_name'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_patient_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_org_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_next_dose_date'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_id'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_medical_attentions_vet_id'), table_name='medical_attentions')
    op.drop_index(op.f('ix_medical_attentions_patient_id'), table_name='medical_attentions')
    op.drop_index(op.f('ix_medical_attentions_org_id'), table_name='medical_attentions')
    op.drop_index(op.f('ix_medical_attentions_id'), table_name='medical_attentions')
    op.drop_table('medical_attentions')
    op.drop_index(op.f('ix_digital_certificates_patient_id'), table_name='digital_certificates')
    op.drop_index(op.f('ix_digital_certificates_org_id'), table_name='digital_certificates')
    op.drop_index(op.f('ix_digital_certificates_id'), table_name='digital_certificates')
    op.drop_index(op.f('ix_digital_certificates_file_hash'), table_name='digital_certificates')
    op.drop_table('digital_certificates')
    op.drop_index(op.f('ix_clinical_records_patient_id'), table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_org_id'), table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_id'), table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_registro_integridad_certificados_id'), table_name='registro_integridad_certificados')
    op.drop_table('registro_integridad_certificados')
    op.drop_index(op.f('ix_professional_identities_id'), table_name='professional_identities')
    op.drop_table('professional_identities')
    op.drop_index(op.f('ix_patients_owner_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_org_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_pet_name'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_owner_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_org_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_index('idx_apps_org_status', table_name='appointments')
    op.drop_index('idx_apps_org_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_org_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_owners_phone_number'), table_name='owners')
    op.drop_index(op.f('ix_owners_org_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_certificados_vacunacion_token_validacion'), table_name='certificados_vacunacion')
    op.drop_index(op.f('ix_certificados_vacunacion_id'), table_name='certificados_vacunacion')
    op.drop_table('certificados_vacunacion')
    op.drop_index(op.f('ix_perfiles_veterinarios_id'), table_name='perfiles_veterinarios')
    op.drop_table('perfiles_veterinarios')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
